### ISSUE TITLE
Add ability to get time delta between PR approval, merge, then publish to production in GitHub

### ISSUE THREAD

**Issue by adrielp** [liatrio/liatrio-otel-collector#63]
# Overview
For metrics on deployments, mirroring the basic DORA metrics, we want to be able to calculate the time delta from pr approval, to merge, to deployment to production.

**Comment by amber-beasley-liatrio** [comment]
We should probably want to capture delta from PR open to PR approved. At current client, I am seeing PR open and stuck open for 1-2 week at a time because of team structure, lack of locally runnable unit testing, newly merged branches causes new PR to not be compatible. 

Knowing if PRs are getting stuck before acceptance could help highlight where the team is missing some basic practices and help up justify spending time on improving those areas.

**Comment by adrielp** [comment]
The correlation of the data will have to be done at the visualization tier. The subjects we need here are: 
* pr open time
* pr creation time
* pr merged time
* pr approval time
* pr deployment tied to merge 

We'll likely need to break this out into separate tasks for each set of metrics

**Comment by adrielp** [comment]
@rhoofard probably should close this one & reference the broken out stories?

**Comment by adrielp** [comment]
Closing this as it's been done for github & gitlab work will be done as separate pieces.
