### ISSUE TITLE
Use the same states variable in the pr count and pr data queries

### ISSUE THREAD

**Issue by adrielp** [liatrio/liatrio-otel-collector#81]
Since we're passing states into the count query, does it make to sense to use the same states variable in this query to ensure the same states are passed into the count & the `getPullRequestData` queries.

_Originally posted by @adrielp in https://github.com/liatrio/liatrio-otel-collector/pull/77#discussion_r1307631699_

**Comment by rhoofard** [comment]
For this I don't think it makes sense just because the reason the state variable exists in the count query is so that we can get the open and merged pr count individually with the same function.  We wouldn't be passing a shared variable between them or the `getPullRequestData` query since there we want both merged and open.

**Comment by adrielp** [comment]
Are we saying that we run the `getPullRequestCount` two times? one per state and assign them to different metric values?

**Comment by adrielp** [comment]
Closing this as done
